[env:nodestick]

extends = nrf52840_base
board = xiao_ble_sense
board_level = pr
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/nodestick
  -I src/platform/nrf52/softdevice
  -I src/platform/nrf52/softdevice/nrf52
  -DNODESTICK
  -DNODESTICK_DEFAULT
  -D CONFIG_NFCT_PINS_AS_GPIOS=1
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/nodestick>
debug_tool = jlink
; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
;upload_protocol = jlink

; Seeed Xiao BLE but with GPS moved to NFC pins, and therefore i2c active
[env:nodestick_i2c]
extends = env:nodestick
board_level = extra
build_flags = ${env:nodestick.build_flags}
  -DNODESTICK
  -DSEEED_NODESTICK_I2C     ; Define I2C variant
  -USEEED_NODESTICK_DEFAULT ; Remove default define
