[env:gumstick]

extends = nrf52840_base
board = xiao_ble_sense
board_level = pr
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/gumstick
  -I src/platform/nrf52/softdevice
  -I src/platform/nrf52/softdevice/nrf52
  -DGUMSTICK
  -DGUMSTICK_DEFAULT
  -D CONFIG_NFCT_PINS_AS_GPIOS=1
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/gumstick>
debug_tool = jlink
; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
;upload_protocol = jlink

; Seeed Xiao BLE but with GPS moved to NFC pins, and therefore i2c active
[env:gumstick_i2c]
extends = env:gumstick
board_level = extra
build_flags = ${env:gumstick.build_flags}
  -DGUMSTICK
  -DSEEED_GUMSTICK_I2C     ; Define I2C variant
  -DSEEED_GUMSTICK_DEFAULT ; Remove default define
